### ISSUE TITLE
vercel 服务部署成功并且配置完 _config.stellar.yml 后依然不生效

### ISSUE THREAD

**Issue by cocoonnu** [xaoxuu/site-info-api#4]
Vercel 服务部署成功并且浏览器测试后能返回数据
```
https://site-info-api-eosin.vercel.app/api/v1?url=https://xaoxuu.com/wiki/stellar
```

然后在 _config.stellar.yml 里面添加了下面的配置
```yml
services:
  siteinfo:
    api: https://site-info-api-eosin.vercel.app/api/v1?url={href}
```

但是在博客中使用link 链接卡片组件并没有生效，查看控制台发现根本没有调用site-info-api-eosin.vercel.app这个接口。所以我感觉还是配置的问题，请问应该怎么解决？

**Comment by xaoxuu** [comment]
<img width="612" alt="Image" src="https://github.com/user-attachments/assets/f5214148-534d-4576-bded-4d3dd325758a" />

<img width="782" alt="Image" src="https://github.com/user-attachments/assets/0095655c-1da7-4216-9259-0fcfde3cbb23" />

我测试了一下有请求且一切正常

**Comment by xaoxuu** [comment]
是配置字段名不对，应该是这样：
```yaml
data_services:
  siteinfo:
    api: https://site-info-api-eosin.vercel.app/api/v1?url={href}
```
